Tests for task1 and task2
georgeee/haskell-itmo-2019-hw3 pull request #1
Opened 2019-04-09 14:56 UTC by sashasashasasha151

I don't think that these tests are good enough, but better then nothing ¯\_(ツ)_/¯

2019-04-12 19:09 UTC, glcanvas commented on task1/longGenerated.sh
> +
![image](https://user-images.githubusercontent.com/22433265/56060416-752ac100-5d6f-11e9-854f-d164d8055a43.png)
я честно говоря хо зэ но кажется это не компилится идеей да и выполняться не хочется особо
![image](https://user-images.githubusercontent.com/22433265/56060482-aa371380-5d6f-11e9-9237-e41af3b8c3a6.png)

2019-04-12 19:20 UTC, sashasashasasha151 commented on task1/longGenerated.sh
> +
это не компилится, потому-что в баше есть поддержка разных присвоений типо b=(echo a) и b=`echo a`, но насм такое поддерживать не надо

2019-04-12 21:12 UTC, pva701 requested changes
@sashasashasasha151 plz consider my comments, it's almost perfect but plz read the new task statement..

2019-04-12 21:12 UTC, pva701 commented on task1/longGenerated.sh
> +$UiO6TNlW OQ$h_VFPdxp$aF'-f3;rg(->V7F7{3$O7Senq8b(WB[W!+$yM55lUi'$Vkri`
@sashasashasasha151 plz update this line correspondingly to new rules regarding brackets in string literals. At the moment this script failed to be parsed due to
```
    |
104 | $UiO6TNlW OQ$h_VFPdxp$aF'-f3;rg(->V7F7{3$O7Senq8b(WB[W!+$yM55lUi'$Vkri`
    |                                ^
unexpected '('
expecting end of input or expression
```

2019-04-12 21:12 UTC, pva701 commented on task1/noQuotes.sh
> +d=q1@#%^&*)(=)+\}{``}?32.,
@sashasashasasha151 update this script too, the error the same:
```
  |
4 | d=q1@#%^&*)(=)+\}{``}?32.,
  |           ^
unexpected ')'
expecting end of input or expression
```

2019-04-12 21:12 UTC, pva701 commented on task2/longGenerated.sh
> +nheVC=Aeut>_`8$jz$<Y<D<{$Qj3$YZm$6SYLOQA$rvVS-PvuV#]q<zGJ=EzDa$2h88OyF$ERtnUlE"0
@sashasashasasha151 this line isn't parsed due to new rule about `$`
```
  |
1 | nheVC=Aeut>_`8$jz$<Y<D<{$Qj3$YZm$6SYLOQA$rvVS-PvuV#]q<zGJ=EzDa$2h88OyF$ERtnUlE"0
  |                   ^
unexpected '<'
expecting '(', '0', or variable name
```

2019-04-13 02:34 UTC, sashasashasasha151 commented
Fix

2019-04-21 23:26 UTC, pva701 commented on task2/longGenerated.sh
> +)$QxRS8eVPr$yCjspMy"n7"$wSi5mV7Uhxv
what is it? it's not a valid string

2019-04-22 08:36 UTC, pva701 approved these changes

2019-04-22 08:37 UTC, merged